name: CD2 - Deploy to Self-Hosted Server (nginx)

on:
  workflow_run:
    workflows: ["CI - Verification HTML"]
    types: [completed]

jobs:
  deploy-server:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Deploy index.html to nginx web root
        run: |
          sudo mkdir -p /var/www/premier-cicd
          sudo cp -f index.html /var/www/premier-cicd/index.html
          sudo chown -R www-data:www-data /var/www/premier-cicd
          sudo nginx -t
          sudo systemctl reload nginx
